# Generated by Django 4.1.7 on 2023-05-13 23:20

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(default='1234567890', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Only digits are allowed.')], verbose_name='National ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sickness', models.CharField(max_length=50)),
                ('watchful_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0, verbose_name='Height (cm)')),
                ('weight', models.IntegerField(default=0, verbose_name='Weight (kg)')),
                ('phone_number', models.CharField(default='+989120000000', max_length=13, validators=[django.core.validators.RegexValidator('^\\+989\\d{9}$', message='Enter valid phone number.(+989)')])),
                ('insurance_type', models.CharField(choices=[('0', 'ٔNo Insurance'), ('1', 'General Health'), ('2', 'Social Supply'), ('3', 'ٔNomads Health')], default='0', max_length=10)),
                ('address', models.CharField(max_length=250)),
                ('blood_type', models.CharField(choices=[('0', 'A+'), ('1', 'A-'), ('2', 'B+'), ('3', 'B-'), ('4', 'O+'), ('5', 'O-'), ('6', 'AB+'), ('7', 'AB-')], max_length=10)),
                ('doctor_order', models.TextField(blank=True)),
                ('nurse_report', models.TextField(blank=True)),
                ('login_at', models.DateTimeField(auto_now_add=True)),
                ('is_hospitalized', models.BooleanField(default=True, verbose_name='Present')),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cost', models.BigIntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Doctors'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='manager.customuser'),
        ),
        migrations.AddField(
            model_name='patient',
            name='nurse',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Nurses'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurse', to='manager.customuser'),
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(choices=[(0, 'ICU'), (1, '1'), (2, '2')], default=1, verbose_name='Floor (0 for ICU)')),
                ('room', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('bed', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.patient')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('is_hospitalized', 'national_id')},
        ),
    ]
