# Generated by Django 4.1.7 on 2023-05-08 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(default=1)),
                ('room', models.IntegerField(default=1)),
                ('bed', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.IntegerField(default=1234567890, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('watchful_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('hight', models.IntegerField(default=170)),
                ('weight', models.IntegerField(default=80)),
                ('phone_number', models.IntegerField(default=9123456789)),
                ('insurance_type', models.CharField(choices=[('0', 'ٔNo Insurance'), ('1', 'General Health'), ('2', 'Social Supply'), ('3', 'ٔNomads Health')], default='0', max_length=10)),
                ('address', models.CharField(max_length=250)),
                ('blood_type', models.CharField(choices=[('0', 'A+'), ('1', 'A-'), ('2', 'B+'), ('3', 'B-'), ('4', 'O+'), ('5', 'O-'), ('6', 'AB+'), ('7', 'AB-')], default='0', max_length=10)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.bed')),
            ],
        ),
    ]
