# Generated by Django 4.1.7 on 2023-05-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone_number',
        ),
    ]
