# Generated by Django 4.1.7 on 2023-05-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_patient_national_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='national_id',
            field=models.BigIntegerField(default=1234567890, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.BigIntegerField(default=9123456789),
        ),
    ]
