# Generated by Django 4.1.7 on 2023-05-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_patient_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='sickness',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
