# Generated by Django 4.1.7 on 2023-05-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_patient_description_patient_sickness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='hight',
            field=models.IntegerField(default=170, verbose_name='Age(cm)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.BigIntegerField(default=1234567890, unique=True, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(default=70, verbose_name='Weight(kg)'),
        ),
    ]
