# Generated by Django 4.1.7 on 2023-05-08 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_rename_name_patient_first_name_patient_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='floor',
            field=models.IntegerField(default=1, verbose_name='Floor (0 for ICU)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bed',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='manager.bed'),
        ),
    ]
