# Generated by Django 4.1.7 on 2023-05-08 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_patient_bed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='bed',
        ),
        migrations.AddField(
            model_name='bed',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.patient'),
        ),
    ]
