# Generated by Django 4.1.7 on 2023-05-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_remove_patient_bed_bed_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='hight',
            new_name='height',
        ),
    ]
