# Generated by Django 4.1.7 on 2023-05-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_rename_hight_patient_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
