# Generated by Django 4.1.7 on 2023-05-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_medicine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
