# Generated by Django 4.1.7 on 2023-05-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_medicine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='description',
            new_name='doctor_order',
        ),
        migrations.AddField(
            model_name='patient',
            name='nurse_report',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
