# Generated by Django 4.1.7 on 2023-05-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_rename_description_patient_doctor_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='description',
            new_name='order',
        ),
    ]
