# Generated by Django 4.1.7 on 2023-05-11 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(choices=[('0', 'A+'), ('1', 'A-'), ('2', 'B+'), ('3', 'B-'), ('4', 'O+'), ('5', 'O-'), ('6', 'AB+'), ('7', 'AB-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.IntegerField(default=0, verbose_name='Age(cm)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(default=1234567890, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='Only digits are allowed.')], verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Weight(kg)'),
        ),
    ]
