# Generated by Django 4.1.7 on 2023-05-11 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_alter_patient_age_alter_patient_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(default='1234567890', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='Only digits are allowed.')], verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='+989123456789', max_length=10, validators=[django.core.validators.RegexValidator('^\\+98\\d{11}$', message='Enter valid phone number.(+98)')]),
        ),
    ]
