# Generated by Django 4.1.7 on 2023-05-11 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0020_patient_doctor_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nurse',
            field=models.OneToOneField(blank=True, limit_choices_to={'groups__name': 'Nurses'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.OneToOneField(blank=True, limit_choices_to={'groups__name': 'Doctors'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
