# Generated by Django 4.1.7 on 2023-05-11 22:33

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('manager', '0021_patient_nurse_alter_patient_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.OneToOneField(blank=True, limit_choices_to={'groups__name': 'Doctors'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='manager.customuser'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nurse',
            field=models.OneToOneField(blank=True, limit_choices_to={'groups__name': 'Nurses'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurse', to='manager.customuser'),
        ),
    ]
