# Generated by Django 4.1.7 on 2023-05-11 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_customuser_alter_patient_doctor_alter_patient_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='+989120000000', max_length=13, validators=[django.core.validators.RegexValidator('^\\+98\\d{11}$', message='Enter valid phone number.(+98)')]),
        ),
    ]
