# Generated by Django 4.1.7 on 2023-05-11 23:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Doctors'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='manager.customuser'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nurse',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Nurses'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurse', to='manager.customuser'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='+989120000000', max_length=13, validators=[django.core.validators.RegexValidator('^\\+989\\d{9}$', message='Enter valid phone number.(+989)')]),
        ),
    ]
