# Generated by Django 4.1.7 on 2023-05-12 00:39

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_alter_patient_doctor_alter_patient_nurse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='login_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(default='1234567890', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Only digits are allowed.')], verbose_name='National ID'),
        ),
    ]
